apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager

# resources:
# - issuer.yaml

helmCharts:
- name: cert-manager
  includeCRDs: true
  repo: https://charts.jetstack.io
  version: v1.15.3
  releaseName: cert-manager
  namespace: cert-manager
  valuesFile: cert-manager.values.yaml
