kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  ipFamily: dual
nodes:
- role: control-plane
- role: worker
  labels:
    role: worker
- role: worker
  labels:
    role: worker
- role: worker
  labels:
    role: worker
