## CONFIGURE KUBE PROXY FOR ARGOCD CONFIGURATION
- name: configure kubeproxy configmap
  ansible.builtin.shell: |
    kubectl get configmap kube-proxy -n kube-system -o yaml | \
    sed -e "s/strictARP: false/strictARP: true/" | \
    kubectl apply -f - -n kube-system
  register: kube_proxy

## CHECK IF KUBE PROXY CONFIGURED SUCCESSFULLY
- name: Check kube proxy
  debug:
    msg: "ArgoCD {{ 'Kube proxy configured successfully' if kube_proxy.failed == false else 'Kube proxy configuration failed' }}"
    # msg: "{{ kube_proxy.failed }}"

## BOOTSTRAP ARGOCD APPLICATIONS
- name: Bootstrap ArgoCD
  ansible.builtin.shell: kubectl apply -f bootstrap/bootstrapper.yaml