# tasks file for talos
# - name: Tap a Homebrew repository, state present
#   community.general.homebrew_tap:
#     name: siderolabs/tap

- name: Install Packages
  ansible.builtin.import_tasks:
    file: install_packages.yaml

- name: Install kind cluster
  ansible.builtin.import_tasks:
    file: install_kind.yaml

- name: Configure ArgoCD
  ansible.builtin.import_tasks:
    file: install_argocd.yaml

- name: Install ArgoCD Applications
  ansible.builtin.import_tasks:
    file: install_argocd_applications.yaml

- name: Configure Load Balancer
  ansible.builtin.import_tasks:
    file: loadbalancer_config.yaml
