# tasks file for talos
# - name: Tap a Homebrew repository, state present
#   community.general.homebrew_tap:
#     name: siderolabs/tap

# INSTALL ALL PACKAGES
- name: Install Packages
  ansible.builtin.import_tasks:
    file: install_packages.yaml

# INSTALL AND INITIATE KIND CLUSTER
- name: Install kind cluster
  ansible.builtin.import_tasks:
    file: install_kind.yaml

# INSTALL AND CONFIGURE ARGOCD
- name: Install ArgoCD
  ansible.builtin.import_tasks:
    file: install_argocd.yaml

# INSTALL AND CONFIGURE ARGOCD APPLICATIONS
- name: Install ArgoCD Applications
  ansible.builtin.import_tasks:
    file: install_argocd_applications.yaml

# INSTALL AND CONFIGURE ARGOCD LOAD BALANCER
- name: Configure Load Balancer
  ansible.builtin.import_tasks:
    file: loadbalancer_config.yaml
