## Official doc - https://strimzi.io/quickstarts/
# Downloaded from - https://strimzi.io/install/latest?namespace=kafka

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: strimzi-kafka

# resources:
# - kafka-operator.yaml


helmCharts:
- name: strimzi-kafka-operator
  includeCRDs: true
  repo: https://strimzi.io/charts/
  version: v0.43.0
  releaseName: strimzi-kafka-operator
  namespace: kafka-system
