apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minio

helmCharts:
- name: minio-operator
  includeCRDs: true
  repo: https://operator.min.io
  version: v4.3.7
  releaseName: minio-operator
  namespace: minio
