auth:
  postgresPassword: "admin@123"
  username: "admin"
  password: "admin@123"
  database: "alembic-demo"
  # existingSecret: ""
  # secretKeys:
  #   adminPasswordKey: postgres-password
  #   userPasswordKey: password
  #   replicationPasswordKey: replication-password