apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minio

helmCharts:
- name: minio
  includeCRDs: true
  repo: https://charts.min.io/
  version: v5.3.0
  releaseName: minio
  namespace: minio
  valuesFile: minio.values.yaml
