apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: ingress-nginx
  includeCRDs: true
  repo: https://kubernetes.github.io/ingress-nginx
  version: v4.12.0
  releaseName: ingress-nginx
  namespace: ingress-nginx
  valuesFile: ingress-nginx.values.yaml
