apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: localstack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc # gke control plane url.Also, argocd can connect to cluster externally .So you can mention multiple clusters like - https://x.x.x.x (gke control plane ip)
    namespace: postgresql
  sources:
  - chart: localstack
    repoURL:  https://helm.localstack.cloud  # note: the oci:// syntax is not included.
    targetRevision: 16.1.2
    # helm:
    #   valueFiles:
    #     - $argo/kubernetes/manifests/postgresql/postgresql.values.yaml
  # - repoURL: https://github.com/defyjoy/spark-kubernetes-minio-data-engineering.git
  #   targetRevision: main
  #   ref: argo
  syncPolicy:
    retry:
      limit: 3 # number of failed sync attempt retries; unlimited number of attempts if less than 0
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 5s # the maximum amount of time allowed for the backoff strategy
    syncOptions:
    - CreateNamespace=true
    - FailOnSharedResource=true
    - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true