apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:

## GitOps
- argocd.yaml

## Ingress Controller
- ingress-nginx.yaml

## Certificates 
- cert-manager.yaml

## Load balancer
- metallb.yaml

## Storage
- minio.yaml

## Databases 
- postgresql.yaml

## Authentication and Authorization
- keycloak.yaml

## AWS
- aws-localstack.yaml

## Distributed processing 
- spark.yaml

## Messaging and Queueing 
- rabbitmq.yaml
- strimzi-kafka.yaml

# CMS 
- wordpress.yaml

## Secret Management 
- hashicorp-vault.yaml

## DNS 
- pihole.yaml
- external-dns.yaml

## AI/ML
- ollama.yaml