apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
- argocd.yaml
- ingress-nginx.yaml
- strimzi-kafka.yaml
- cert-manager.yaml
- spark.yaml
- metallb.yaml
- minio.yaml
- postgresql.yaml
- keycloak.yaml
- aws-localstack.yaml
- rabbitmq.yaml
- hashicorp-vault.yaml
- pihole.yaml
- external-dns.yaml
- wordpress.yaml