apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc # gke control plane url.Also, argocd can connect to cluster externally .So you can mention multiple clusters like - https://x.x.x.x (gke control plane ip)
    namespace: postgresql
  sources:
    - repoUrl: https://github.com/defyjoy/spark-kubernetes-minio-data-engineering.git
      targetRevision: main
      ref: argo
    - chart: postgresql
      repoURL: registry-1.docker.io/bitnamicharts  # note: the oci:// syntax is not included.
      targetRevision: 17.0.0
      helm:
      valueFiles:
        - $argo/kubernetes/apps/postgresql.values.yaml