apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


helmCharts:
- name: spark
  includeCRDs: true
  repo: https://charts.bitnami.com/bitnami
  version: v9.2.10
  releaseName: spark
  namespace: spark
  # valuesFile: dev.values.yaml
