apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-address-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.68.255/30
  # - 172.18.0.255/30
  - fc00:f853:ccd:e799::/124
  autoAssign: true
