apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# resources:
# - ../../base
helmCharts:
- name: ingress-nginx
  includeCRDs: true
  repo: https://kubernetes.github.io/ingress-nginx
  version: v4.4.2
  releaseName: ingress-nginx
  namespace: ingress-nginx
  # valuesFile: dev.values.yaml
